# Standard imports
import sys
from pathlib import Path
import fnmatch
import pandas as pd
import pytest
import os
import shutil
import tempfile
from PIL import Image

# Import functions to test
from src.utils.data_utils import (
    apply_row_id_config,
    get_subset,
    validate_metadata,
    validate_proteindata,
    combine_plots,
    combine_csv_files,
)

# Add project root to sys.path to allow relative import resolution
sys.path.append(str(Path(__file__).resolve().parents[1]))

# ————————————————————————————————————————————
# Tests for apply_row_id_config()
# ————————————————————————————————————————————

def test_apply_row_id_config_phospho_fields_present():
    """
    Test that phospho row IDs are generated by combining index and specified fields.
    - Missing fields should be replaced with 'NA' as per config.
    - Final index format: <index>__<field1>_<field2>.
    """
    df = pd.DataFrame({
        "site": ["S10", "T20", None],
        "modification": ["phospho", "phospho", "acetyl"]
    }, index=["P1", "P2", "P3"])

    config = {
        "data_type": "phospho",
        "phospho_row_id": {
            "fields": ["site", "modification"],
            "missing_value": "NA"
        }
    }

    result = apply_row_id_config(df.copy(), config)

    # Expect site and modification to be appended to the original index
    expected_index = [
        "P1__S10_phospho",
        "P2__T20_phospho",
        "P3__NA_acetyl"  # 'site' is None -> replaced by "NA"
    ]
    assert list(result.index) == expected_index


def test_apply_row_id_config_non_phospho():
    """
    Test that non-phospho data_type skips row ID transformation.
    Function should return DataFrame unchanged.
    """
    df = pd.DataFrame({"A": [1, 2]}, index=["X", "Y"])
    config = {"data_type": "other"}
    result = apply_row_id_config(df.copy(), config)
    assert result.equals(df)


def test_apply_row_id_config_missing_field():
    """
    Test that only available fields are used to generate new index.
    Missing fields in config are silently ignored.
    """
    df = pd.DataFrame({
        "site": ["S10", "T20"]
    }, index=["P1", "P2"])

    config = {
        "data_type": "phospho",
        "phospho_row_id": {
            "fields": ["site", "modification"],  # 'modification' is missing
            "missing_value": "NA"
        }
    }

    result = apply_row_id_config(df.copy(), config)

    # Only 'site' is used; no 'modification' column available
    expected_index = ["P1__S10", "P2__T20"]
    assert list(result.index) == expected_index


def test_apply_row_id_config_no_fields():
    """
    If no fields are specified in config, function should return DataFrame unchanged.
    """
    df = pd.DataFrame({"A": [1, 2]}, index=["X", "Y"])
    config = {
        "data_type": "phospho",
        "phospho_row_id": {"fields": []}
    }
    result = apply_row_id_config(df.copy(), config)
    assert result.equals(df)


# ————————————————————————————————————————————
# Tests for get_subset()
# ————————————————————————————————————————————

def test_get_subset_success():
    """
    Test that get_subset() correctly filters columns based on metadata values.
    - Input data has columns A_rep1, A_rep2, B_rep1.
    - Subset by 'treatment' == 'A' -> returns A_rep1, A_rep2 only.
    """
    df = pd.DataFrame({
        "A_rep1": [1.0, 2.0],
        "A_rep2": [1.5, 2.5],
        "B_rep1": [3.0, 4.0],
    }, index=["Prot1", "Prot2"])

    metadata = pd.DataFrame({
        "sample_rep": ["A_rep1", "A_rep2", "B_rep1"],
        "treatment": ["A", "A", "B"],
    })

    result = get_subset(df, "A", metadata, "treatment")

    assert list(result.columns) == ["A_rep1", "A_rep2"]
    assert result.shape == (2, 2)


def test_get_subset_no_match():
    """
    Test that ValueError is raised when no metadata rows match the subset term.
    """
    df = pd.DataFrame({
        "A_rep1": [1.0, 2.0],
        "B_rep1": [3.0, 4.0],
    }, index=["Prot1", "Prot2"])

    metadata = pd.DataFrame({
        "sample_rep": ["A_rep1", "B_rep1"],
        "treatment": ["A", "B"],
    })

    with pytest.raises(ValueError, match="No matches found for subset: C"):
        get_subset(df, "C", metadata, "treatment")


# ————————————————————————————————————————————
# Tests for validate_metadata()
# ————————————————————————————————————————————

def good_metadata():
    """
    Return a valid example metadata DataFrame for use in multiple tests.
    """
    return pd.DataFrame({
        "sample_id": ["S1", "S2"],
        "treatment": ["Ctl", "Drug"],
        "replicate": [1, 2],
        "protein_abundance_name": ["col1", "col2"],
        "sample_rep": ["S1_1", "S2_1"]
    })


def test_validate_metadata_passes():
    """
    Basic test: all required columns are present and valid.
    Should pass without raising.
    """
    validate_metadata(good_metadata())


def test_missing_column_raises():
    """
    Test that missing required columns raise a ValueError.
    """
    df = good_metadata().drop(columns="treatment")
    with pytest.raises(ValueError, match="Missing required columns"):
        validate_metadata(df)


def test_nan_raises():
    """
    Test that missing values (NaN) in required columns raise a ValueError.
    """
    df = good_metadata()
    df.loc[1, "sample_id"] = None
    with pytest.raises(ValueError, match="contains missing"):
        validate_metadata(df)


def test_duplicate_sample_replicate_pair_raises():
    """
    Duplicate sample_id + replicate combinations are not allowed.
    """
    df = good_metadata()
    df.loc[1, "sample_id"] = "S1"
    df.loc[1, "replicate"] = 1
    df.loc[1, "sample_rep"] = "S1_1"
    with pytest.raises(ValueError, match="must be unique"):
        validate_metadata(df)


def test_nonnumeric_replicate_raises():
    """
    Replicate must be numeric (int or float), not string.
    """
    df = good_metadata()
    df["replicate"] = ["one", "two"]
    with pytest.raises(ValueError, match="'replicate' must be numeric"):
        validate_metadata(df)


def test_duplicate_protein_abundance_name_raises():
    """
    Duplicated protein_abundance_name values should raise an error.
    """
    df = good_metadata()
    df.loc[1, "protein_abundance_name"] = "col1"
    with pytest.raises(ValueError, match="must not contain duplicate"):
        validate_metadata(df)


# ————————————————————————————————————————————
# Tests for validate_proteindata()
# ————————————————————————————————————————————

def test_empty_data_raises():
    """
    Protein data must not be empty — raise ValueError if it is.
    """
    df = pd.DataFrame()
    meta = pd.DataFrame({"sample_rep": []})
    with pytest.raises(ValueError, match="data is empty"):
        validate_proteindata(df, meta)


def test_duplicate_protein_ids_case_insensitive():
    """
    Protein identifiers in index must be unique — case insensitive check.
    """
    df = pd.DataFrame({"s1": [1], "s2": [2]}, index=["GeneA", "genea"])
    meta = pd.DataFrame({
        "sample_rep": ["s1", "s2"],
        "protein_abundance_name": ["s1", "s2"]
    })
    with pytest.raises(ValueError, match="Protein identifiers.*unique"):
        validate_proteindata(df, meta)


def test_column_metadata_mismatch_raises():
    """
    Sample columns in data must match sample_rep in metadata.
    """
    df = pd.DataFrame({"S1": [1], "S2": [2]}, index=["Gene1"])
    meta = pd.DataFrame({"sample_rep": ["S1", "S3"]})
    with pytest.raises(ValueError, match="Mismatch between metadata samples"):
        validate_proteindata(df, meta)


def test_non_numeric_values_raises():
    """
    All protein abundance values must be numeric (int/float).
    """
    df = pd.DataFrame({"S1": [1], "S2": ["bad"]}, index=["Gene1"])
    meta = pd.DataFrame({"sample_rep": ["S1", "S2"]})
    with pytest.raises(ValueError, match="non-numeric"):
        validate_proteindata(df, meta)


def test_missing_values_raises():
    """
    Presence of NaN in protein data should trigger a UserWarning.
    """
    df = pd.DataFrame({"S1": [1], "S2": [float("nan")]}, index=["Gene1"])
    meta = pd.DataFrame({"sample_rep": ["S1", "S2"]})
    with pytest.warns(UserWarning, match="contains missing"):
        validate_proteindata(df, meta)


# ————————————————————————————————————————————
# Tests for combine_plots()
# ————————————————————————————————————————————

@pytest.fixture
def image_dir_with_pngs():
    """
    Create a temporary directory with subfolders, each containing a dummy volcano_plot.png.
    """
    temp_dir = tempfile.mkdtemp()
    subdir1 = os.path.join(temp_dir, "group1")
    subdir2 = os.path.join(temp_dir, "group2")
    os.makedirs(subdir1)
    os.makedirs(subdir2)

    # Save identical dummy image in both subdirs
    for subdir in [subdir1, subdir2]:
        img = Image.new("RGB", (100, 100), color=(255, 0, 0))
        img.save(os.path.join(subdir, "volcano_plot.png"))

    yield temp_dir
    shutil.rmtree(temp_dir)


def test_combine_plots_creates_output(image_dir_with_pngs):
    """
    Test that combine_plots finds and tiles images, saving to expected output path.
    """
    output_dir = tempfile.mkdtemp()

    combine_plots(
        search_term="volcano_plot.png",
        search_path=image_dir_with_pngs,
        output_dir=output_dir,
        img_size=(100, 100),
        max_cols=2
    )

    # Final path based on default combine logic
    combined_path = os.path.join(output_dir, "plots", "combined_volcano_plot.png")
    assert os.path.exists(combined_path)

    with Image.open(combined_path) as img:
        assert img.size[0] >= 100  # width
        assert img.size[1] >= 100  # height

    shutil.rmtree(output_dir)


# ————————————————————————————————————————————
# Tests for combine_csv_files()
# ————————————————————————————————————————————

@pytest.fixture
def mock_csv_structure():
    """
    Create a temp directory with two treatment folders, each with a top_hits.csv file.
    """
    temp_dir = tempfile.mkdtemp()
    os.makedirs(os.path.join(temp_dir, "DrugA"))
    os.makedirs(os.path.join(temp_dir, "DrugB"))

    # Simulate two CSV files with top gene hits
    df1 = pd.DataFrame({
        "gene": ["G1", "G2", "G3"],
        "logFC": [1.5, -0.8, 2.1],
        "pval": [0.01, 0.05, 0.03]
    })
    df2 = pd.DataFrame({
        "gene": ["G4", "G5", "G6"],
        "logFC": [-2.0, 0.7, 1.1],
        "pval": [0.02, 0.06, 0.01]
    })

    df1.to_csv(os.path.join(temp_dir, "DrugA", "top_hits.csv"), index=False)
    df2.to_csv(os.path.join(temp_dir, "DrugB", "top_hits.csv"), index=False)

    yield temp_dir
    shutil.rmtree(temp_dir)


def test_combine_csv_files_outputs_combined(mock_csv_structure):
    """
    Verify that combine_csv_files merges top-N rows from multiple files
    and adds a 'treatment_pair' column to distinguish them.
    """
    combine_csv_files(
        filename="top_hits.csv",
        output_dir=mock_csv_structure,
        top_n=2,
        new_column="treatment_pair"
    )

    # Combined file should be written to data/combined_top_hits.csv
    combined_path = os.path.join(mock_csv_structure, "data", "combined_top_hits.csv")
    assert os.path.exists(combined_path)

    df = pd.read_csv(combined_path)
    assert df.shape[0] == 4  # 2 rows from each file
    assert "treatment_pair" in df.columns
    assert set(df["treatment_pair"]) == {"DrugA", "DrugB"}
