name: Tests
on:
  push:
    branches: [stable, staging]
  pull_request:
    branches: [stable, staging]
jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  # activates conda for all steps
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: configs/auto-prot-env-macOS.yml
          activate-environment: myenv
          miniforge-version: latest
          use-mamba: true
      - run: pip install -e ".[dev]"
      - run: pytest
